# Generated by Django 6.0 on 2026-01-12 14:28

import apps.products.models.product
import apps.products.models.variation_type
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.products.models.product.image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='departments.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='departments.department')),
            ],
            options={
                'permissions': [('sell_product', 'Can sell product')],
            },
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('select', 'Select'), ('radio', 'Radio'), ('image', 'Image')], default='select', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_types', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariationTypeOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.variationtype')),
            ],
        ),
        migrations.CreateModel(
            name='VariationTypeOptionImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.products.models.variation_type.image_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('variation_type_option', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variationtypeoption')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variation_type_option', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variation_type_option', 'product'), name='unique_product_variation')],
            },
        ),
        migrations.AddConstraint(
            model_name='variationtype',
            constraint=models.UniqueConstraint(fields=('name', 'product'), name='unique_variation_type_name'),
        ),
        migrations.AddConstraint(
            model_name='variationtypeoption',
            constraint=models.UniqueConstraint(fields=('name', 'variation_type'), name='unique_variation_type_option_name'),
        ),
    ]
