# Generated by Django 6.0 on 2026-01-13 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='departments.department'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
        migrations.AddField(
            model_name='variationtype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_types', to='products.product'),
        ),
        migrations.AddField(
            model_name='variationtypeoption',
            name='variation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.variationtype'),
        ),
        migrations.AddField(
            model_name='variationtypeoptionimage',
            name='variation_type_option',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variationtypeoption'),
        ),
        migrations.AddConstraint(
            model_name='productvariation',
            constraint=models.UniqueConstraint(fields=('variation_type_option', 'product'), name='unique_product_variation'),
        ),
        migrations.AddConstraint(
            model_name='variationtype',
            constraint=models.UniqueConstraint(fields=('name', 'product'), name='unique_variation_type_name'),
        ),
        migrations.AddConstraint(
            model_name='variationtypeoption',
            constraint=models.UniqueConstraint(fields=('name', 'variation_type'), name='unique_variation_type_option_name'),
        ),
    ]
