# Generated by Django 6.0 on 2026-01-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationtypeoption',
            name='variation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.variationtype'),
        ),
        migrations.AlterField(
            model_name='variationtypeoptionimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
