# Generated by Django 6.0 on 2026-01-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationtypeoptionimage',
            name='variation_type_option',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variationtypeoption'),
        ),
    ]
