# Generated by Django 6.0 on 2026-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variationtypeoptionimage_variation_type_option'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariation',
            constraint=models.UniqueConstraint(fields=('variation_type_option', 'product'), name='unique_product_variation'),
        ),
    ]
