# Generated by Django 6.0 on 2026-01-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariation_unique_product_variation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variationtype',
            constraint=models.UniqueConstraint(fields=('name', 'product'), name='unique_variation_type_name'),
        ),
        migrations.AddConstraint(
            model_name='variationtypeoption',
            constraint=models.UniqueConstraint(fields=('name', 'variation_type'), name='unique_variation_type_option_name'),
        ),
    ]
