# Generated by Django 6.0 on 2026-01-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variationtype_unique_variation_type_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationtypeoptionimage',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='variationtypeoptionimage',
            name='unique_variation_option_image_order',
        ),
    ]
