# Generated by Django 6.0 on 2026-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
