# Generated by Django 6.0 on 2025-12-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationtype',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('radio', 'Radio'), ('image', 'Image')], default='select', max_length=100),
        ),
    ]
