# Generated by Django 6.0 on 2026-01-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Suspended')], default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Suspended')], default=True),
        ),
    ]
