# Generated by Django 6.0 on 2025-12-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_variationtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationtypeoption',
            name='variation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='products.variationtype'),
        ),
    ]
