# Generated by Django 6.0 on 2025-12-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('buy_product', 'Can buy product'), ('sell_product', 'Can sell product')]},
        ),
    ]
