# Generated by Django 6.0 on 2026-01-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_department_status_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationtypeoption',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
